[package]
name = "advent"
version = "0.1.0"
authors = ["Mike Cooper <mythmon@gmail.com>"]

[dependencies]
rand = "*"
regex = "*"
lazy_static = "*"

[lib]
name = "advent"
path = "src/lib.rs"

[[bin]]
name = "day01_part1"
path = "src/day01/part1.rs"

[[bin]]
name = "day01_part2"
path = "src/day01/part2.rs"

[[bin]]
name = "day02_part1"
path = "src/day02/part1.rs"

[[bin]]
name = "day02_part2"
path = "src/day02/part2.rs"

[[bin]]
name = "day03_part1"
path = "src/day03/part1.rs"

[[bin]]
name = "day03_part2"
path = "src/day03/part2.rs"

[[bin]]
name = "day04_part1"
path = "src/day04/part1.rs"

[[bin]]
name = "day04_part2"
path = "src/day04/part2.rs"

[[bin]]
name = "day05_part1"
path = "src/day05/part1.rs"

[[bin]]
name = "day05_part2"
path = "src/day05/part2.rs"

[[bin]]
name = "day06_part1"
path = "src/day06/part1.rs"

[[bin]]
name = "day06_part2"
path = "src/day06/part2.rs"

[[bin]]
name = "day07_part1"
path = "src/day07/part1.rs"

[[bin]]
name = "day07_part2"
path = "src/day07/part2.rs"

[[bin]]
name = "day08_part1"
path = "src/day08/part1.rs"

[[bin]]
name = "day08_part2"
path = "src/day08/part2.rs"

[[bin]]
name = "day09_part1"
path = "src/day09/part1.rs"

[[bin]]
name = "day09_part2"
path = "src/day09/part2.rs"

[[bin]]
name = "day10_part1"
path = "src/day10/part1.rs"

[[bin]]
name = "day10_part2"
path = "src/day10/part2.rs"

[[bin]]
name = "day11_part1"
path = "src/day11/part1.rs"

[[bin]]
name = "day11_part2"
path = "src/day11/part2.rs"

[[bin]]
name = "day12_part1"
path = "src/day12/part1.rs"

[[bin]]
name = "day12_part2"
path = "src/day12/part2.rs"

[[bin]]
name = "day13_part1"
path = "src/day13/part1.rs"

[[bin]]
name = "day13_part2"
path = "src/day13/part2.rs"

[[bin]]
name = "day14_part1"
path = "src/day14/part1.rs"

[[bin]]
name = "day14_part2"
path = "src/day14/part2.rs"

[[bin]]
name = "day15_part1"
path = "src/day15/part1.rs"

[[bin]]
name = "day15_part2"
path = "src/day15/part2.rs"

[[bin]]
name = "day16_part1"
path = "src/day16/part1.rs"

[[bin]]
name = "day16_part2"
path = "src/day16/part2.rs"

[[bin]]
name = "day17_part1"
path = "src/day17/part1.rs"

[[bin]]
name = "day17_part2"
path = "src/day17/part2.rs"

[[bin]]
name = "day18_part1"
path = "src/day18/part1.rs"

[[bin]]
name = "day18_part2"
path = "src/day18/part2.rs"

[[bin]]
name = "day19_part1"
path = "src/day19/part1.rs"

[[bin]]
name = "day19_part2"
path = "src/day19/part2.rs"

[[bin]]
name = "day20_part1"
path = "src/day20/part1.rs"

[[bin]]
name = "day20_part2"
path = "src/day20/part2.rs"

[[bin]]
name = "day21_part1"
path = "src/day21/part1.rs"

[[bin]]
name = "day21_part2"
path = "src/day21/part2.rs"

[[bin]]
name = "day22_part1"
path = "src/day22/part1.rs"

[[bin]]
name = "day22_part2"
path = "src/day22/part2.rs"

[[bin]]
name = "day23_part1"
path = "src/day23/part1.rs"

[[bin]]
name = "day23_part2"
path = "src/day23/part2.rs"

[[bin]]
name = "day24_part1"
path = "src/day24/part1.rs"

[[bin]]
name = "day24_part2"
path = "src/day24/part2.rs"
