cargo-features = ["default-run"]

[package]
name = "advent"
version = "2017.25.1"
authors = ["Mike Cooper <mythmon@gmail.com>"]
edition = "2018"
default-run = "advent"

[dependencies]
rand = "^0.3.18"
regex = "^0.2.3"
lazy_static = "^1.0.0"
colored = "^1.6.1"
indoc = "^0.2"
rayon = "^1.0.3"

[profile.release]
incremental = true
overflow-checks = true

[lib]
name = "advent"
path = "src/lib.rs"

[[bin]]
name = "advent"
path = "src/bin.rs"