[package]
name = "advent2017"
version = "0.1.0"
authors = ["Mike Cooper <mythmon@gmail.com>"]

[dependencies]

[[bin]]
name = "day1_part1"
path = "src/day1/part1.rs"

[[bin]]
name = "day1_part2"
path = "src/day1/part2.rs"
