[workspace]
members = ["advent-lib", "advent-runner", "year*"]
default-members = ["advent-runner"]

# Most of the running is in release mode, to make puzzles go fast. So turn on
# some niceties that debug mode includes.
[profile.release]
incremental = true
overflow-checks = true
