#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(deprecated)]

use crate::year2018::day03::Claim;

grammar;

// input looks like: #1 @ 1,3: 4x4
pub Claim: Claim = {
    "#" <id: u32> "@" <x: usize> "," <y: usize> ":" <w: usize> "x" <h: usize> => Claim { id, x, y, w, h },
}

usize: usize = {
    <s:r"[0-9]+"> => s.parse().unwrap()
};

u32: u32 = {
    <s:r"[0-9]+"> => s.parse().unwrap()
};
